notify slack on master fail
brimsec/zq pull request #1986
Opened 2021-01-18 23:12 UTC by mattnibs

2021-01-18 23:46 UTC, marktwallace commented
The changes to the workflow look easier than I expected. I saw Slack under installed GitHub apps, but I do not see how to configure it. Is it admin only?

2021-01-19 21:40 UTC, mattnibs commented
Here's what the slack message will look like:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/2147549/105096259-cacbeb80-5a74-11eb-95eb-b2902f025d7b.png">

We cannot test this on this repository: webhook initiated events only trigger when they workflow is in the default branch. I did create a test repository that uses this exact yaml and it works: https://github.com/mattnibs/githubactions/blob/main/.github/workflows/workflow.yml

2021-01-19 21:41 UTC, mattnibs commented
> The changes to the workflow look easier than I expected. I saw Slack under installed GitHub apps, but I do not see how to configure it. Is it admin only?

@marktwallace the only configuration is the `SLACK_WEBHOOK_BRIMLABS_TEST` secret that @philrz was kind enough to setup for me. It contains a slack uri that posts messages to channel #test

2021-01-19 21:45 UTC, philrz requested changes

2021-01-19 21:45 UTC, philrz commented on .github/workflows/notify-master-failure.yml
> +      - name: Inform Slack users at Brim HQ of the new artifact
Looks like copypasta. 😉

2021-01-19 22:17 UTC, philrz commented on .github/workflows/notify-master-failure.yml
> +              "text": "Workflow \"${{ github.event.workflow_run.name }}\" failed on master.\n${{ github.event.workflow_run.html_url }}"
Does `html_url` point to the failed run? The docs at https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#workflow_run don't seem to describe this field.

2021-01-19 22:25 UTC, mattnibs commented on .github/workflows/notify-master-failure.yml
> +      - name: Inform Slack users at Brim HQ of the new artifact
```suggestion
      - name: Notify Brim HQ of failure on master
```

2021-01-19 23:37 UTC, philrz approved these changes

2021-01-19 23:41 UTC, merged